### ISSUE TITLE
Integration appears fully broken now :)

### ISSUE THREAD

**Issue by mafrosis** [safepay/sensor.willyweather#24]
```
home-assistant-1  | 2024-07-06 12:05:39.528 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ww_temperature fails
home-assistant-1  | Traceback (most recent call last):
home-assistant-1  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
home-assistant-1  |     await self.async_device_update()
home-assistant-1  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
home-assistant-1  |     await hass.async_add_executor_job(self.update)
home-assistant-1  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
home-assistant-1  |     result = self.fn(*self.args, **self.kwargs)
home-assistant-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-1  |   File "/config/custom_components/willyweather/sensor.py", line 239, in update
home-assistant-1  |     self._data.update()
home-assistant-1  |   File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 186, in wrapper
home-assistant-1  |     result = method(*args, **kwargs)
home-assistant-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-1  |   File "/config/custom_components/willyweather/sensor.py", line 311, in update
home-assistant-1  |     self._data = result['observational']
home-assistant-1  |                  ~~~~~~^^^^^^^^^^^^^^^^^
home-assistant-1  | KeyError: 'observational'
```

**Comment by safepay** [comment]
Resolved with rewrite.
